### ISSUE TITLE
how to add new feeds directly to another backend?

### ISSUE THREAD

**Issue by hisham2007** [scripting/river5#10]
Many thanks for great work. I have a use case and I don't know how to implement it.

I have a backend as a service (Parse / Firebase) and i want that every time a new feed exists, it should be added to my backend.  

so i don't need river5 web page. i want callback to directly call a web service in my backend every time there is a new data

Thank you for support

**Comment by scripting** [comment]
Sorry for the delay in responding. 

It sounds like there are two questions here.

1. How to add a feed to the list of subscribed-to feeds. There's a good way to do this, it involves understanding how OPML works. I'll write this up separately and add a pointer here.

2. How to call a web service when there's new data. There's a folder in your river5 installation called "callbacks" and in there is a sub-folder called addToRiver. Any .js files in that folder will run when a river is built. Two globals are set for each call, fname and jsontext. That should be enough data for you to pass through to another web service. 

There's another approach for #2 that's even easier -- use the websockets interface.  Do a view-source on this page for an idea of how it works. 

http://rss2.io/code/socketdemo/

Back in a bit with the howto for #1.

**Comment by scripting** [comment]
Here's the howto -- 

https://github.com/scripting/river5/blob/master/docs/DROPBOXSUBSCRIPTIONLISTS.md

Dave
