### ISSUE TITLE
How do I display the RSS feed chronoligically

### ISSUE THREAD

**Issue by younes-io** [scripting/river5#19]
I've added a few RSS feeds, but I want them to be displayed from most recent to oldest, and not the opposite.

I've considered the config file but couldn't find an attribute to do that.

**Comment by htheriault** [comment]
This would be very handy. Preferable as a default, even. It might have something to do with these bits from includes/feedviewer/code.js

`const lastUpdateFormat = "%A, %B %e, %Y at %l:%M %p";`

...

`var pubDateString = formatDate (item.pubDate, lastUpdateFormat) + ".";
	add ("<div class=\"divContentPubDateLine\">" + pubDateString + "</div>");
	`
But that's just a mostly uneducated guess on my part.
