### ISSUE TITLE
Broken umlauts in feeds

### ISSUE THREAD

**Issue by ChristophKnopf** [scripting/river5#20]
Hello,

nice work crafting river5 and share it with us! Thank you.

Unfortunately I got a problem with umlauts. If the RSS feed contains any umlauts they will be not displayed correctly. Feeds incoming are looking good, so the encoding is changed while parsed by river5.
Did a quick look, but didn't find the right spot for now, will have a closer look later. Maybe you can give me a hint or you have the time to fix it.

Anyway thanks in advance.

**Comment by scripting** [comment]
I'm glad that River5 is proving useful.

If you want me to look into the problem I need to be able to reproduce it here. 

First piece of info I need is the feed that causes the error. 

Then some kind of indication of what's going wrong.

See the [How to ask for help with software](http://scripting.com/2014/03/19/howToAskForHelpWithSoftware.html) doc.

**Comment by ChristophKnopf** [comment]
Hello Mr. Winter,

thanks fort he repsonse and sorry I did not provide the additional information.
You can pick one or all of the following feeds:
https://www.presseportal.de/rss/dienststelle_110972.rss2
https://www.presseportal.de/rss/dienststelle_116093.rss2
https://www.presseportal.de/rss/dienststelle_110975.rss2
https://www.presseportal.de/rss/dienststelle_75292.rss2
https://www.presseportal.de/rss/dienststelle_14915.rss2

As I said I did not had the time to look deeper , but my first guess would be that the encoding will be changed when the XML is parsed.
You can also have a look at our site which uses your awesome tool http://rss.bnn.de .

Another question: Is it planed  to run river5 under https protocol, as browsers are changing thei security standards? Should I ask this in public?

Thanks in advance and greetings.

Mit freundlichen Grüßen
Christoph Knopf

Badische Neueste Nachrichten
Badendruck GmbH

Aufbauteam Digital | Web Developer
Linkenheimer Landstraße 133, 76149 Karlsruhe
Telefon: +49(721)789-213 | Telefax:
E-Mail: cknopf@bnn.de | Web: bnn.de<http://bnn.de>

Firmensitz: Linkenheimer Landstraße 133, D-76149 Karlsruhe
Registergericht: Amtsgericht Mannheim, HRB 100194
Geschäftsführer: Klaus Michael Baur, Rüdiger Quenzer

[cid:image001.png@01D3BB76.2D6DC520]

Besuchen Sie uns auch auf Facebook, Twitter, YouTube und Instagram.
[Facebook]<https://www.facebook.com/badischeneuestenachrichten>  [cid:image003.png@01D3BB76.2D6DC520] <https://twitter.com/BNN_BaNeuNa/>   [cid:image004.png@01D3BB76.2D6DC520] <http://www.youtube.com/c/BadischeNeuesteNachrichtenBadendruckGmbH>   [cid:image005.png@01D3BB76.2D6DC520] <https://www.instagram.com/badische_neueste_nachrichten/>
Von: Dave Winer [mailto:notifications@github.com]
Gesendet: Dienstag, 13. März 2018 14:59
An: scripting/river5 <river5@noreply.github.com>
Cc: Christoph Knopf <cknopf@bnn.de>; Author <author@noreply.github.com>
Betreff: Re: [scripting/river5] Broken umlauts in feeds (#20)


I'm glad that River5 is proving useful.

If you want me to look into the problem I need to be able to reproduce it here.

First piece of info I need is the feed that causes the error.

Then some kind of indication of what's going wrong.

See the How to ask for help with software<http://scripting.com/2014/03/19/howToAskForHelpWithSoftware.html> doc.

**Comment by ChristophKnopf** [comment]
Hi Dave,

big thanks for the update!
unlikely if I try to run a `npm update` (node v4.8.7) I get an error:
```
npm ERR! iconv@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.
```
Did a rebuild without success.
Can you/anyone please confirm that?

Greetings christoph

**Comment by scripting** [comment]
Hell o Christoph. I don't know what the problem is, but I posted a couple of suggestions in this post. 

http://scripting.com/2018/04/16/143346.html

Hopefully other people who can help will tune in.

**Comment by scripting** [comment]
Anton reports success achieved by changing permissions on some file??

https://github.com/scripting/river5/issues/21#issuecomment-381623181

**Comment by mistersugar** [comment]
This was the file: river5/lib/node_modules/npm/bin/node-gyp-bin/node-gyp

**Comment by scripting** [comment]
I was able to replace iconv with iconv-lite in River5, so if you have been having trouble installing, it makes sense to try again.

**Comment by ChristophKnopf** [comment]
Hi Dave,

reinstalled river5 and it works now (with umlauts, yeah).
Thank you and have a nice weekend.

Greetings christoph
