### ISSUE TITLE
Displaying several columns in one tab/panel

### ISSUE THREAD

**Issue by TsterRM** [scripting/river5#29]
Hello,

I'm interested in displaying more than one column on a single tab/panel.
Which file/folder should I be looking at to accomplish this? Thanks!

**Comment by andysylvester** [comment]
Can you give a little more description of what "more than one column on a single tab/panel" means? If you have added multiple lists in the River5 lists folder, you should see a tab for each list. Are you asking how to display multiple rivers next to each other?

**Comment by TsterRM** [comment]
@andysylvester Not exactly. For example, let's say I have the river "ESPN" and it displays all the breaking stories from the sporting world. Rather than 1 view, I would like to have 2 or 3  columns that are populated with the ESPN rss feed. See pictures as an example:
[https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/three-column-wordpress-themes.jpg](url)

**Comment by scripting** [comment]
@TsterRM -- I can see the utility of something like that, but that's not really something River5 does. It's about aggregations of feeds. You want to display a single feed. You have to start somewhere else. And you really do have to be a programmer to do that. Or hire one. ;-)

**Comment by TsterRM** [comment]
@scripting Understood, thank you very much for your input. I appreciate it!
